AllCops:
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
    - lib/tasks/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - Gemfile
    - Rakefile

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - '**/*_spec.rb'

Style/BlockDelimiters:
  Enabled: false
  Exclude:
    - '**/*_spec.rb'

Lint/AmbiguousBlockAssociation:
  Enabled: false
